### ISSUE TITLE
Pull in latest changes from upstream dd-trace project

### ISSUE THREAD

**Issue by akshah123** [lightstep/ls-trace-rb#6]
There has been many improvements made to dd-trace library since last time this repo was forked.

Some of the key feature enhancements are:
* support for Ruby 2.7
* Faraday 1.0 support
* Auto tagging enhancements
* Performance improvements

It would be great if it was possible to pull in these enhancements into this project.

**Comment by mwear** [comment]
This was done in #7 and released as [ls-trace v0.2.0](https://rubygems.org/gems/ls-trace/versions/0.2.0)

**Comment by bmulholland** [comment]
@mwear The docs still say that ruby 2.7 isn't supported: https://docs.lightstep.com/docs/ruby-auto-instrumentation
